repos:
- repo: local
  hooks:
    - id: check-dependencies
      name: Check for mix.lock divergences
      always_run: true
      pass_filenames: false
      language: system
      entry: "mix"
      args: ["deps.get"]
    - id: formatter
      name: Format Elixir files
      files: ".*\\.exs?"
      language: system
      entry: "mix"
      args: ["format"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.1.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: mixed-line-ending
    - id: check-json
    - id: pretty-format-json
      args: ["--autofix"]
